version: '3'
services:
  dbs:
    hostname: retoapp_dbs
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
    volumes:
      - ./dbs-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    hostname: retoapp_web
    build: .
    env_file: .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - dbs

# volumes:
#   retoapp-dbs-data: {}
